<a href="https://colab.research.google.com/github/rajob16/Python-Course/blob/main/SUST_Edge_PP02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python

> ### Rajob Tarek Hasan

## Generators

### What are Generators?
Generators are functions that return an iterator and allow you to iterate through a sequence of values lazily (on demand) using the `yield` keyword.

Key Benefits:
1. Memory Efficient: They don’t store all elements in memory.
2. Lazy Evaluation: Values are produced when needed.
3. Simplifies Iterators: Easier to write compared to building a custom iterator class.

In [ ]:
nums = [1,2,3,4]

# for i in nums:
#   print(i)

def nums_generator():
    for i in nums:
        yield i

gen = nums_generator()

print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))

In [ ]:
# A basic generator example
def number_generator():
    for i in range(1, 4):
        yield i

# Create the generator
gen = number_generator()

# Get values from the generator
print(next(gen))  # 1
print(next(gen))  # 2
print(next(gen))  # 3

### Exercise
Create a generator function that returns even numbers from 1 to 10.

In [ ]:
def even_number_generator():
    # Your code here
    for i in range(1, 10):
        if i % 2 == 0:
            yield i

gen = even_number_generator()
print(next(gen))  # 2
print(next(gen))  # 4

### Generator Expressions
Generator expressions provide a concise way to create a generator without the need for a separate function. They look like list comprehensions but use parentheses `()` instead of square brackets `[]`.

They are memory-efficient because they generate items on demand.

In [ ]:
# Generator expression for squares of numbers
squares = (x**2 for x in range(1, 6))
print(next(squares))  # 1
print(next(squares))  # 4

### Exercise
Write a generator expression to create cubes of numbers from 1 to 5.

In [ ]:
# Your code here
cubes = (x**3 for x in range(1, 100000000000))
print(next(cubes))

## Closures

### What are Closures?
A closure is a function that "remembers" the environment in which it was created. If a function is defined inside another function and uses variables from the enclosing scope, it becomes a closure.

Closures are useful for maintaining state across function calls.

In [ ]:
def outer_function(x):
    def inner_function(y):
        return x + y
    return inner_function

closure = outer_function(10)
print(closure(5))  # 15

In [ ]:
def power_outer(x):
  def power_inner(y):
    return y**x
  return power_inner

square = power_outer(2)
print(square(10))
cube = power_outer(3)
print(cube(10))

### Exercise
Write a closure that keeps track of how many times it has been called.

In [ ]:
def counter():
    c = 0
    def make_count():
      nonlocal c
      c += 1
      return c
    return make_count

count = counter()
print(count())  # 1
print(count())  # 2

count2 = counter()
print(count2())
print(count())

## Decorators

### What are Decorators?
Decorators are functions that modify the behavior of other functions. They are applied to functions using the `@decorator_name` syntax.

Use Cases:
- Logging
- Timing functions
- Authorization checks

In [ ]:
def greet_decorator(func):
    def wrapper():
        print("Hello!")
        func()
        print("Goodbye!")
    return wrapper


@greet_decorator
def ordinary():
  print("Something ordinary")


@greet_decorator
def ordinary2():
  print("Something ordinary2")

ordinary()
ordinary2()

In [ ]:
def greet_decorator(func):
    def wrapper():
        print("Hello!")
        func()
        print("Goodbye!")
    return wrapper

@greet_decorator
def my_function():
    print("I am learning decorators!")

my_function()

### Exercise
Write a decorator that times how long a function takes to execute.

In [ ]:
from time import time

In [ ]:
# Your code here
def timer_decorator(func):
  def wrapper():
    start_time = time()
    ret_val = func()
    end_time = time()
    print("Elapsed Time: ", end_time - start_time)
    return ret_val

  return wrapper

In [ ]:
@greet_decorator
@timer_decorator
def my_function():
    print("I am learning decorators!")

my_function()

In [ ]:
@timer_decorator
def loop10000():
  sum = 0
  for i in range(1000):
    sum += 10000
  return sum

print(loop10000())

## File Handling

### Basic File Operations
File handling in Python allows you to open, read, write, and manage files.

In [ ]:
# Writing to a file
with open("example.txt", "w") as file:
    file.write("Hello, File Handling!")

# Reading from a file
with open("example.txt", "r") as file:
    content = file.read()
    print(content)  # Output: Hello, File Handling!

### Renaming and Deleting Files

The `os` module provides methods for renaming and deleting files.

In [ ]:
import os

In [ ]:
import os

# Renaming a file
os.rename("example.txt", "renamed_example.txt")

# Deleting a file
os.remove("renamed_example.txt")

### Accessing Directories

You can create, delete, and navigate directories using the `os` module.

In [ ]:
import os

# Create a new directory
os.mkdir("new_directory")

# Change the current working directory
os.chdir("new_directory")
print("Current Directory:", os.getcwd())

# Delete the directory
os.chdir("..")
os.rmdir("new_directory")

### File Methods

Python files support various methods like `read()`, `write()`, and `seek()` for file operations.

In [ ]:
with open("example.txt", "w+") as file:
    file.write("Hello, World!")
    file.seek(2)
    print(file.read())  # Output: Hello, World!

### OS File/Directory Methods

The `os` module also provides advanced methods for file and directory handling.

In [ ]:
os.mkdir("folder1")
with open("folder1/tex1.txt", "w") as file:
  file.write("Test 1 2 3")

In [ ]:
os.getcwd()

In [ ]:
os.path.getsize("example.txt")

In [ ]:
import os

# List all files in the current directory
print(os.listdir("."))

# Check if a file exists
print(os.path.exists("example.txt"))

# Get file size
print(os.path.getsize("example.txt"))

In [ ]:
def student_generator():
  with open("students.txt", "r") as student_file:
    for line in student_file:
      yield(line.strip().split(","))

gen = student_generator()
print(next(gen))
print(next(gen))
print(next(gen))

### Fun Exercise

Write a program that:
1. Creates a directory called "test_dir".
2. Creates a file inside it called "test_file.txt" and writes "Hello, Python!" into it.
3. Reads the content back and prints it.
4. Deletes the file and directory.

In [ ]:
# Your code here

## Summary

- **Generators**: Efficient, lazy iterators for sequences.
- **Closures**: Functions that remember their creation context.
- **Decorators**: Functions to modify behavior of other functions.
- **File Handling**: Read, write, and manage files and directories.

## Numpy

### What is NumPy?
- NumPy (Numerical Python) is a library used for numerical and matrix operations.
- It provides high-performance multidimensional arrays.
- Key Features:
  - Supports vectorized operations (faster than loops).
  - Ideal for mathematical and scientific computing.


### Creating Arrays

In [ ]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


### ndarray
The `ndarray` is the core data structure of NumPy. It represents a multidimensional, homogeneous array of fixed-size items.

Key Properties:
1. `ndim`: Number of dimensions.
2. `shape`: Shape (size of each dimension).
3. `dtype`: Data type of the array elements.

In [ ]:
# Creating an ndarray
arr = np.array([[[1,2], [2,3]], [[3,4], [4,5]]], dtype="float64")
print("Array:\n", arr)

# Properties of ndarray
print("Number of Dimensions:", arr.ndim)
print("Shape of Array:", arr.shape)
print("Data Type:", arr.dtype)


Array:
 [[[1. 2.]
  [2. 3.]]

 [[3. 4.]
  [4. 5.]]]
Number of Dimensions: 3
Shape of Array: (2, 2, 2)
Data Type: float64


### Data Type Objects (`dtype`)
The `dtype` object specifies the type of data stored in an array (e.g., integer, float, etc.).

Key Features:
1. Allows custom data types.
2. Supports advanced types like complex numbers and fixed-length strings.

In [ ]:
# Array with default integer dtype
arr = np.array([1, 2, 3])
print("Default dtype:", arr.dtype)

# Array with custom dtype
arr_float = np.array([1, 2, 3], dtype="float64")
print("Custom dtype:", arr_float.dtype)

# Complex dtype
arr_complex = np.array([1 + 2j, 3 + 4j])
print("Complex dtype:", arr_complex.dtype)

Default dtype: int64
Custom dtype: float64
Complex dtype: complex128


### Array Operations

In [ ]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Scaler operations
print("Array + 10:", arr + 10)
print("Array * 2:", arr * 2)

# Mathematical operations
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())

# Element-wise operations
print("Addition:", arr + arr2)
print("Multiplication:", arr * arr2)

Array + 10: [11 12 13 14]
Array * 2: [2 4 6 8]
Sum: 10
Mean: 2.5
Max: 4
Addition: [ 6  8 10 12]
Multiplication: [ 5 12 21 32]


### Array Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# Accessing elements
print("First Element:", arr[0])
print("Last Element:", arr[-1])

# Slicing
print("First 3 Elements:", arr[1:3])
print("Last 2 Elements:", arr[-2:])

Original Array: [10 20 30 40 50]
First Element: 10
Last Element: 50
First 3 Elements: [20 30]
Last 2 Elements: [40 50]


### Advanced Indexing

In [ ]:
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])

print(arr.ndim)
print(arr.shape)

print("Specific Elements: ", arr[-1])
print("Boolean Masking:", arr[arr % 20 == 0])

2
(3, 2)
Specific Elements:  [50 60]
Boolean Masking: [20 40 60]


### Exercise
1. Create a NumPy array of numbers from 1 to 10.
2. Multiply every element by 3.
3. Find the mean and maximum of the array.

In [ ]:
nums = np.arange(1, 11)

mult_nums = nums * 3

print(mult_nums.mean())
print(mult_nums.max())

16.5
30


### Iterating Over Arrays
You can iterate over an ndarray using Python loops. For multidimensional arrays:
1. Iterate row by row.
2. Use `nditer` for element-wise iteration.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Row-wise iteration
for row in arr:
    print("Row:", row)

# Element-wise iteration
for element in np.nditer(arr):
    print("Element:", element)

### Linear Algebra
NumPy provides linear algebra functions like dot products, matrix multiplication, and determinants.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]], dtype="float64")
arr2 = np.array([[5, 6], [7, 8]], dtype="float64")

print("Arr 1\n",arr1)
print("Arr 2\n",arr2)

print("Dot\n",np.dot(arr1, arr2))

print("Transpose\n",arr1.T)

round(np.linalg.det(arr1), 3)

Arr 1
 [[1. 2.]
 [3. 4.]]
Arr 2
 [[5. 6.]
 [7. 8.]]
Dot
 [[19. 22.]
 [43. 50.]]
Transpose
 [[1. 3.]
 [2. 4.]]


-2.0

In [ ]:
# Dot product
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(arr1, arr2))

# Transpose of a matrix
print("Transpose:\n", arr1.T)

# Determinant
print("Determinant:", np.linalg.det(arr1))

### Sorting, Searching, and Counting
NumPy provides functions to sort arrays, search for values, and count elements.

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9])

# Sorting
print("Sorted Array:", np.sort(arr))

# Searching
print("Index of 1:", np.where(arr == 1))

# Counting
print("Count of 1s:", np.count_nonzero(arr == 1))

Sorted Array: [1 1 3 4 5 9]
Index of 4: (array([1, 3]),)
Count of 1s: 2


### Exercise
1. Create a 2D NumPy array of random integers between 1 and 50.
2. Perform the following:
   - Find the mean of all elements.
   - Transpose the array.
   - Sort the array along rows.
   - Extract all elements greater than 25.
3. Perform matrix multiplication between the original and transposed array.


In [ ]:
rand_arr = np.random.randint(1, 51, size=(3,3))

print("Random Array\n", rand_arr)
print("Mean", rand_arr.mean())
print("Transpose\n", rand_arr.T)
print("Sorted along Rows\n", np.sort(rand_arr, axis=1))
print("Elements greater than 25\n", rand_arr[rand_arr > 25])
print(np.dot(rand_arr, rand_arr.T))

Random Array
 [[44 42 24]
 [36 12 45]
 [30 40 30]]
Mean 33.666666666666664
Transpose
 [[44 36 30]
 [42 12 40]
 [24 45 30]]
Sorted along Rows
 [[24 42 44]
 [12 36 45]
 [30 30 40]]
Elements greater than 25
 [44 42 36 45 30 40 30]
[[4276 3168 3720]
 [3168 3465 2910]
 [3720 2910 3400]]


## Task: NumPy Task: Analyzing a 2D Array

- Create a 2D NumPy array of shape (4, 5) with random integers between 10 and 60.
- Perform the following operations:
  - Extract the first two rows.
  - Extract all elements in the last column.
  - Replace all elements greater than 30 with 0.
  - Calculate the sum of all elements in the array after replacement.
  - Find the mean of each row.
  - Add another row
- Print the result after each step